version: '3.1'

services:

  db:
    container_name: database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ".env"
#    environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: example
   network_mode: "host"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
#    network_mode: "host"

  tgbot:
    container_name: bot
    build:
      context: .
    command: python3.7 app.py
    restart: always
    env_file:
        - ".env"
